apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app # Nombre a gusto propio
  namespace: argocd  # Namespace donde se instala argocd por defecto
spec:
  project: default
  source:
    repoURL: https://github.com/matosxxl/basic-k8s-intec # Repositorio Git que observara ArgoCD
    targetRevision: master  # Rama a revisar por cambios
    path: "."  # Ubicacion del repo donde se alojan los manifiestos (archivos de kubernetes)
  destination:
    server: https://kubernetes.default.svc  # Ubicacion por defecto de la API de Kubernetes
    namespace: default  # Namespace donde desplegaremos la aplicacion
    # En caso de especificar uno diferente a default, asegurarnos que ya este previamente creado
    # kubectl create namespace {{NOMBRE_DE_TU_NAMESPACE}}
  syncPolicy:
    automated:
      prune: true # Determina la accion a tomar cuando hay cambios en la rama
      selfHeal: true # Determina si al detectar que hay errores se puede auto diagnosticar y solucionar
