apiVersion: v1
kind: Service
metadata:
  name: landing-service
spec:
  type: NodePort
  selector:
    app: landing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081