apiVersion: v1
kind: Service
metadata:
  name: movil-service
spec:
  type: NodePort
  selector:
    app: bank-mobil
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30083