apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-bank-page
spec:
  strategy:
    type: Recreate
  replicas: 2
  selector:
    matchLabels:
      app: landing
  template:
    metadata: 
      labels:
        app: landing
    spec:
      containers:
        - name: landing-bank-page-pod
          image:  nginx
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
