apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-banking
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bank-mobil
  template:
    metadata: 
      labels:
        app: bank-mobil
    spec:
      containers:
        - name: mobile-banking-pod
          image:  nginx
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
